using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using ProjectEulerInCSharp;
using System.Diagnostics;

namespace ProjectEulerTests
{
    [TestClass]
    public class UnitTests
    {
        [TestMethod]
        public void Problem1Test1()
        {
            //If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. 
            //The sum of these multiples is 23.
            Solutions euler = new Solutions();
            Int32 result = euler.SumOfMultiplesOfThreeOrFive(10);

            Assert.AreEqual(23, result);
        }

        [TestMethod]
        public void Problem1Solution()
        {
            //Find the sum of all the multiples of 3 or 5 below 1000.
            Solutions euler = new Solutions();
            Stopwatch watch = Stopwatch.StartNew();
            Int32 result = euler.SumOfMultiplesOfThreeOrFive(1000);

            watch.Stop();

            Console.WriteLine(String.Format("Problem {0} = {1}  ({2}ms)", 1, result, watch.ElapsedMilliseconds));
           
            Assert.AreEqual(233168, result);
        }

        [TestMethod]
        public void Problem2Test1()
        {
            //Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
            //By starting with 1 and 2, the first 10 terms will be:
            //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

            Solutions euler = new Solutions();
            Assert.AreEqual(1, euler.FibonacciNumber(1));
            Assert.AreEqual(2, euler.FibonacciNumber(2));
            Assert.AreEqual(3, euler.FibonacciNumber(3));
            Assert.AreEqual(5, euler.FibonacciNumber(4));
            Assert.AreEqual(8, euler.FibonacciNumber(5));
            Assert.AreEqual(13, euler.FibonacciNumber(6));
            Assert.AreEqual(21, euler.FibonacciNumber(7));
            Assert.AreEqual(34, euler.FibonacciNumber(8));
            Assert.AreEqual(55, euler.FibonacciNumber(9));
            Assert.AreEqual(89, euler.FibonacciNumber(10));

        }

        [TestMethod]
        public void Problem2Solution()
        {
            Solutions euler = new Solutions();
           //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            Stopwatch watch = Stopwatch.StartNew();
            Int32 result = euler.SumOfEvenFibonacciNumbers(4000000);
          
            watch.Stop();
            Console.WriteLine(String.Format("Problem {0} = {1}  ({2}ms)", 2, result, watch.ElapsedMilliseconds));

            Assert.AreEqual(4613732, result);
        }
    }
}
