namespace ProjectEulerInFSharp

open Math
open Extensions

module Solutions =


    // If we list all the natural numbers below 10 that are
    // multiples of 3 or 5, we get 3, 5, 6 and 9. The sum
    // of these multiples is 23.
    let Problem1Example () =
        [1 .. 9]
        |> Seq.filter (fun n -> n.DividesBy(3) || n.DividesBy(5))
        |> Seq.sum;

    // Find the sum of all the multiples of 3 or 5 below 1000
    let Problem1Solution () =
        [1 .. 999]
        |> Seq.filter (fun n -> n.DividesBy(3) || n.DividesBy(5))
        |> Seq.sum;

    // Each new term in the Fibonacci sequence is generated by
    // adding the previous two terms. By starting with 1 and 2,
    // the first 10 terms will be:
    //
    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //
    // By considering the terms in the Fibonacci sequence whose
    // values do not exceed four million, find the sum of the
    // even-valued terms.
    let Problem2Solution () =
        InfiniteFibonacciSequence ()
        |> Seq.takeWhile (fun n -> n < 4000000)
        |> Seq.filter (fun n -> n.DividesBy(2))
        |> Seq.sum


    // The prime factors of 13195 are 5, 7, 13 and 29.


    // What is the largest prime factor of the number 600851475143 ?
        
